#' Correct errors in the peptide feature dataframes.
#'
#' @param featureDFList A list of feature dataframes generated by \code{Features}.
#' @param TCRSet Either a set of TCR sequences (as a character vector) or a list of sets of TCR sequences. If provided as a list, it must be the same length with the seedSet.
#' @param fragLenSet A set of the lengths of TCR sequence fragments to be matched against the peptide set.
#' @param aaIndexIDSet A set of AAIndexIDs indicating the pairwise matching score matrix to be used. A set of AAIndex-derived matrices can be retrieved by \code{AACPMatrix}. Set "all" to select all AAIndexIDs.
#' @param alignTypeSet A set of alignment-type strings directly passed to the \code{type} argument of the \code{pairwiseAlignment} function in the \code{Biostrings} package.
#' @param TCRFragDepthSet A set of the numbers of TCR fragments to be matched. This should be kept constant for comparison.
#' @param seedSet A set of random seeds.
#' @importFrom rlang is_empty
#' @importFrom DescTools Sort
#' @importFrom dplyr filter
#' @importFrom data.table rbindlist
#' @importFrom tibble as_tibble
#' @export
#' @rdname Features_ErrorCorrect
#' @name Features_ErrorCorrect
Features_ErrorCorrect <- function(
  featureDFList, TCRSet,
  fragLenSet=3:8, aaIndexIDSet="all",
  alignTypeSet="global-local", TCRFragDepthSet=10000,
  seedSet=1:5
){
  errPeptSet <- sort(unique(unlist(lapply(featureDFList, function(df){as.character(df[which(complete.cases(df)==F),][["Peptide"]])}))))
  message("Error peptides: ", paste0(errPeptSet, collapse=", "))
  if(rlang::is_empty(errPeptSet)){ return(featureDFList) }
  featureDFList_ErrorCorrect <- Features(peptideSet=errPeptSet, TCRSet, aaIndexIDSet, alignTypeSet, fragLenSet, TCRFragDepthSet, seedSet)
  featureDFList_Others <- lapply(featureDFList, function(df){dplyr::filter(df, !Peptide %in% errPeptSet)})
  featureDFList_ErrorCorrect <- mapply(function(df_Org, df_EC){tibble::as_tibble(DescTools::Sort(data.table::rbindlist(list(df_Org, df_EC)), ord="Peptide"))},
                                       featureDFList_Others, featureDFList_ErrorCorrect, SIMPLIFY=F)
  return(featureDFList_ErrorCorrect)
}
