#' Generate peptide features.
#'
#' \code{Features_PeptDesc} calculates descriptive statistics of peptide descriptors.\cr
#' \code{Features_CPP} calculates descriptive statistics of interresidue pairwise contact potential profiles.\cr
#' \code{Features} is a wrapper function.
#'
#' @param peptideSet A set of peptide sequences.
#' @param fragLib Either the dataframe of fragment libraries generated by \code{CPP_FragmentLibrary} or the path to the fst file.
#' @param aaIndexIDSet A set of AAIndex IDs indicating the AACP scales to be used. Set "all" to shortcut the selection of all available AACP scales.
#' @param fragLenSet A set of sliding window sizes. Must be between 3 and 8.
#' @param fragDepthSet A set of fragment library sizes. Must be below 100000.
#' @param fragLibTypeSet A set of strings indicating the types of fragment libraries to be used.
#' @param featureSet A minimum set of features. Combinations of fragment lengths and AAIndex IDs are internally extracted for calculating CPPs.
#' @param seedSet A set of random seeds.
#' @param coreN The number of cores to be used for parallelization. Set \code{NULL} to skip parallelization.
#' @param tmpDir Destination directory to save intermediate files.
#' @importFrom dplyr %>%
#' @importFrom dplyr mutate
#' @importFrom dplyr select
#' @importFrom dplyr filter
#' @importFrom dplyr left_join
#' @importFrom tidyr gather
#' @importFrom tidyr spread
#' @importFrom tidyr unite
#' @importFrom tidyr crossing
#' @importFrom data.table :=
#' @importFrom data.table CJ
#' @importFrom data.table as.data.table
#' @importFrom data.table transpose
#' @importFrom data.table rbindlist
#' @importFrom data.table setorder
#' @importFrom data.table setcolorder
#' @importFrom data.table melt.data.table
#' @importFrom data.table dcast.data.table
#' @importFrom fst read_fst
#' @importFrom fst write_fst
#' @importFrom magrittr set_names
#' @importFrom magrittr set_colnames
#' @importFrom Biostrings reverse
#' @importFrom Biostrings pairwiseAlignment
#' @importFrom Biostrings AA_STANDARD
#' @importFrom stringr str_sub
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_split
#' @importFrom stringr str_detect
#' @importFrom stringr fixed
#' @importFrom psych describe
#' @importFrom matrixStats rowMins
#' @importFrom matrixStats rowMaxs
#' @importFrom matrixStats rowMeans2
#' @importFrom matrixStats rowMedians
#' @importFrom parallel detectCores
#' @importFrom parallel detectCores
#' @importFrom parallel makeCluster
#' @importFrom parallel clusterEvalQ
#' @importFrom parallel clusterExport
#' @importFrom parallel stopCluster
#' @importFrom pbapply pbapply
#' @importFrom pbapply pblapply
#' @importFrom snow clusterSetupRNGstream
#' @import Peptides
#' @export
#' @rdname Features
#' @name Features_PeptDesc
Features_PeptDesc <- function(
  peptideSet,
  fragLenSet=3:8,
  featureSet=NULL
){
  # Start calculation
  set.seed(12345)
  time.start <- proc.time()

  # Working functions
  peptideDescriptor.Batch <- function(peptide){
    unlist(list(
      Peptides::aIndex(peptide),
      Peptides::blosumIndices(peptide),
      Peptides::boman(peptide),
      Peptides::charge(peptide),
      Peptides::crucianiProperties(peptide),
      Peptides::fasgaiVectors(peptide),
      Peptides::hmoment(peptide),
      Peptides::hydrophobicity(peptide),
      Peptides::instaIndex(peptide),
      Peptides::kideraFactors(peptide),
      Peptides::mswhimScores(peptide),
      Peptides::pI(peptide),
      Peptides::protFP(peptide),
      Peptides::vhseScales(peptide),
      Peptides::zScales(peptide)
    ))
  }
  peptideDescriptor.NameSet <- c("AliphaticIndex","BLOSUM1","BLOSUM2","BLOSUM3","BLOSUM4","BLOSUM5","BLOSUM6","BLOSUM7","BLOSUM8","BLOSUM9","BLOSUM10","Boman","Charge","PP1","PP2","PP3","F1","F2","F3","F4","F5","F6","HydrophobicMoment","Hydrophobicity","Instability","KF1","KF2","KF3","KF4","KF5","KF6","KF7","KF8","KF9","KF10","MSWHIM1","MSWHIM2","MSWHIM3","pI","ProtFP1","ProtFP2","ProtFP3","ProtFP4","ProtFP5","ProtFP6","ProtFP7","ProtFP8","VHSE1","VHSE2","VHSE3","VHSE4","VHSE5","VHSE6","VHSE7","VHSE8","Z1","Z2","Z3","Z4","Z5")
  peptideDescriptor.FragStat.Single <- function(peptide, fragLen){
    f <- sapply(1:(max(nchar(peptide))-fragLen+1), function(i){stringr::str_sub(peptide, i, i+fragLen-1)})
    d <- sapply(f[nchar(f)==fragLen], function(s){peptideDescriptor.Batch(s)})
    data.frame("Peptide"=peptide,
               "FragLen"=fragLen,
               "AADescriptor"=peptideDescriptor.NameSet,
               "Min"=matrixStats::rowMins(d),
               "Max"=matrixStats::rowMaxs(d),
               "Mean"=matrixStats::rowMeans2(d),
               "Median"=matrixStats::rowMedians(d))
  }

  # Parallelized calculation of descriptive statistics
  parameterDF <- tidyr::crossing(peptideSet, fragLenSet)
  cl <- parallel::makeCluster(parallel::detectCores(), type="SOCK")
  parallel::clusterExport(
    cl=cl,
    list("parameterDF", "peptideDescriptor.FragStat.Single", "peptideDescriptor.Batch", "peptideDescriptor.NameSet"),
    envir=environment()
  )
  df_feature <- pbapply::pbapply(
    parameterDF, 1,
    function(v){peptideDescriptor.FragStat.Single(v[1], as.numeric(v[2]))},
    cl=cl
  )
  parallel::stopCluster(cl)
  gc();gc();

  # Formatting
  df_feature <- data.table::rbindlist(df_feature) %>%
    tidyr::gather(Stat, Value, -Peptide, -FragLen, -AADescriptor) %>%
    tidyr::unite(Feature, AADescriptor, Stat, FragLen, sep="_") %>%
    tidyr::spread(Feature, Value)
  colnames(df_feature) <- paste0("PeptDesc_", colnames(df_feature))
  colnames(df_feature)[1] <- "Peptide"

  # Basic peptide information
  df_basic <- data.frame("Peptide"=peptideSet, "Peptide_Length"=nchar(peptideSet))
  for(aa in Biostrings::AA_STANDARD){
    df_basic[[paste0("Peptide_Contain", aa)]] <- as.numeric(stringr::str_detect(peptideSet, aa))
  }
  df_feature <- suppressWarnings(dplyr::left_join(df_basic, df_feature, by="Peptide"))
  rownames(df_feature) <- 1:nrow(df_feature)
  dt_pept <- data.table::as.data.table(df_feature)

  # Minimum set of features (optional)
  if(!is.null(featureSet)){
    featureSet <- intersect(colnames(dt_pept), featureSet)
    dt_pept <- dt_pept[, c("Peptide", featureSet), with=F]
  }

  # Finish the timer
  time.end <- proc.time()
  message("Overall time required = ", format((time.end-time.start)[3], nsmall=2), "[sec]")

  # Clear logs
  rm(list=setdiff(ls(), c("dt_pept")))
  gc();gc()

  # Output
  return(dt_pept)
}

#' @export
#' @rdname Features
#' @name Features_CPP
Features_CPP <- function(
  peptideSet,
  fragLib,
  aaIndexIDSet="all",
  fragLenSet=3:8,
  fragDepthSet=10000,
  fragLibTypeSet=c("Deduplicated", "Weighted", "Mock"),
  featureSet=NULL,
  seedSet=1:5,
  coreN=parallel::detectCores(),
  tmpDir=file.path(tempdir(), "FeatureDF", format(Sys.time(), "%Y.%m.%d.%H.%M.%S"))
){
  # Temp directory check
  dir.create(tmpDir, showWarnings=F, recursive=T)

  # Start calculation
  set.seed(12345)
  time.start <- proc.time()

  # Pairwise contact potential matrix
  AACPMatrixList <- CPP_AACPMatrix()
  if(identical(aaIndexIDSet, "all")){
    aaIndexIDSet <- names(AACPMatrixList)
  }else{
    aaIndexIDSet <- sort(unique(c(aaIndexIDSet, stringr::str_replace(paste0(aaIndexIDSet, "inv"), "invinv", "inv"))))
    AACPMatrixList <- AACPMatrixList[aaIndexIDSet]
  }

  # Fragment library for alignment
  if(is.character(fragLib)) fragLib <- fst::read_fst(fragLib)

  # Contact potential profiling
  if(is.null(featureSet)){
    parameterDT <- data.table::CJ(peptideSet, aaIndexIDSet, fragLenSet, fragDepthSet, fragLibTypeSet) %>%
      magrittr::set_colnames(c("Peptide","AAIndexID","FragLen","FragDepth","Library"))
    data.table::setorder(parameterDT)
  }else{
    cjdt <- function(a,b){
      cj = data.table::CJ(1:nrow(a), 1:nrow(b))
      cbind(a[cj[[1]],], b[cj[[2]],])
    }
    featureDT <- strsplit(grep("^CPP_", featureSet, value=T), "_") %>%
      data.table::as.data.table() %>%
      data.table::transpose() %>%
      dplyr::select(V2, V4) %>%
      magrittr::set_colnames(c("AAIndexID", "FragLen")) %>%
      dplyr::distinct(.keep_all=T)
    featureDT[,FragLen:=as.integer(FragLen)]
    parameterDT <- data.table::CJ(peptideSet, fragDepthSet, fragLibTypeSet) %>%
      magrittr::set_colnames(c("Peptide","FragDepth","Library"))
    parameterDT <- cjdt(parameterDT, featureDT)
    data.table::setcolorder(parameterDT, c("Peptide","AAIndexID","FragLen","FragDepth","Library"))
    data.table::setorder(parameterDT)
  }
  message("Number of parameter combinations = ", nrow(parameterDT))
  message("Launching parallel clusters...")
  if(is.null(coreN)) coreN <- 1
  cl <- parallel::makeCluster(coreN, type="SOCK")
  parallel::clusterExport(
    cl=cl,
    list("parameterDT","AACPMatrixList","fragLib"),
    envir=environment()
  )
  message("Contact potential profiling...")
  cpp <- function(clusterObject, seedNumber=12345){
    snow::clusterSetupRNGstream(clusterObject, seed=rep(seedNumber, 6))
    dt <- pbapply::pblapply(
      1:nrow(parameterDT),
      function(i){
        pept <- parameterDT[[i,1]]
        aaIndexID <- parameterDT[[i,2]]
        aacpMat <- AACPMatrixList[[aaIndexID]]
        fragLen <- parameterDT[[i,3]]
        fragDepth <- parameterDT[[i,4]]
        libraryType <- parameterDT[[i,5]]
        libraryID <- paste0(c(libraryType, fragLen, seedNumber), collapse="_")
        fragSet <- sample(fragLib[[libraryID]], size=fragDepth)
        al <- Biostrings::pairwiseAlignment(
          subject=pept, pattern=fragSet,
          substitutionMatrix=aacpMat,
          type="global-local", gapOpening=100, gapExtension=100,
          scoreOnly=T
        )
        statSet <- c("mean","sd","median","trimmed","mad","skew","kurtosis","se","IQR","Q0.1","Q0.9")
        stat <- psych::describe(al, trim=.1, interp=F, skew=T, type=3, ranges=T, IQR=T, quant=c(.10, .90))[statSet]
        return(as.numeric(stat))
      }, cl=clusterObject) %>%
      as.data.frame() %>%
      data.table::as.data.table() %>%
      data.table::transpose()
    colnames(dt) <- c("Mean","SD","Med","TrM","MAD","Skew","Kurt","SE","IQR","Q10","Q90")
    parameterDT[,"Seed":=seedNumber]
    dt <- cbind(parameterDT, dt)
    fst::write_fst(dt, file.path(tmpDir, paste0("dt_feature_cpp_seed", seedNumber, ".fst")))
    return(dt)
  }
  dt_cpp_filenames <- list.files(pattern="dt_feature_cpp_seed.+fst", path=tmpDir, full.names=F)
  if(length(dt_cpp_filenames)>=1){
    seedSet_done <- as.numeric(gsub("seed", "", gsub(".fst", "", t(as.data.frame(strsplit(dt_cpp_filenames, "_"), fix.empty.names=F))[,4], fixed=T)))
    message(" - Skipping random seeds ", paste0(seedSet_done, collapse=", "))
    seedSet <- setdiff(seedSet, seedSet_done)
  }
  for(s in seedSet){
    cat("Random seed = ", s, "\n", sep="")
    cpp(cl, seedNumber=s)
    gc();gc()
  }
  parallel::stopCluster(cl)
  gc();gc()

  ## Final formatting
  message("Data formatting...")
  dt_cpp_filenames <- list.files(pattern="dt_feature_cpp_seed.+fst", path=tmpDir, full.names=T)
  dt_cpp <- data.table::rbindlist(lapply(dt_cpp_filenames, fst::read_fst, as.data.table=T))
  data.table::setorder(dt_cpp, Peptide, AAIndexID, FragLen, FragDepth, Library, Seed)
  col_id <- c("Peptide", "AAIndexID", "FragLen", "FragDepth", "Library", "Seed")
  col_val <- setdiff(colnames(dt_cpp), col_id)
  dt_cpp <- data.table::melt.data.table(dt_cpp, id=col_id, measure=col_val, variable.name="Stat", value.name="Value")
  dt_cpp[,"Feature":=paste0("CPP_", AAIndexID, "_", Stat, "_", FragLen)][,"AAIndexID":=NULL][,"FragLen":=NULL][,"Stat":=NULL]
  dt_cpp <- data.table::dcast.data.table(dt_cpp, Peptide+FragDepth+Library~Feature, value.var="Value", fun=mean)
  if(!is.null(featureSet)){
    featureSet <- intersect(colnames(dt_cpp), featureSet)
    dt_cpp <- dt_cpp[, c("Peptide", "FragDepth", "Library", featureSet), with=F]
  }

  # Finish the timer
  time.end <- proc.time()
  message("Overall time required = ", format((time.end-time.start)[3], nsmall=2), "[sec]")

  # Clear logs
  rm(list=setdiff(ls(), c("dt_cpp")))
  gc();gc()

  # Output
  return(dt_cpp)
}

#' @export
#' @rdname Features
#' @name Features
Features <- function(
  peptideSet,
  fragLib,
  aaIndexIDSet="all",
  fragLenSet=3:8,
  fragDepthSet=10000,
  fragLibTypeSet=c("Deduplicated", "Weighted", "Mock"),
  featureSet=NULL,
  seedSet=1:5,
  coreN=parallel::detectCores(),
  tmpDir=file.path(tempdir(), "FeatureDF", format(Sys.time(), "%Y.%m.%d.%H.%M.%S"))
){
  message("Peptide contact potential profiling analysis...")
  dt_cpp <- Features_CPP(peptideSet, fragLib, aaIndexIDSet, fragLenSet, fragDepthSet, fragLibTypeSet, featureSet, seedSet, coreN, tmpDir)
  message("Peptide descriptor analysis...")
  dt_pept <- Features_PeptDesc(peptideSet, fragLenSet, featureSet)
  message("Merging...")
  dt <- merge(dt_pept, dt_cpp, by="Peptide")
  dt[,"FragDepth":=format(FragDepth, trim=T, scientific=F)]
  return(split(dt, by=c("Library", "FragDepth"), keep.by=F))
}
