#' Decode parameters used for calculating the minimum set of features.
#'
#' \code{Features_DecodeParameters} obtains a set of parameters required for calculation of the minimum set of features used in \code{preprocessedDFList_reference}.\cr
#' \code{Features_Minimum} allows users to generate a set of preprocessed feature dataframes for different sets of peptides and TCR repertoires based on the parameters obtianed by \code{Features_DecodeParameters}.
#'
#' @param preprocessedDFList_reference A list of feature dataframes generated by \code{Features_Preprocess} for reference.
#' @importFrom stringr str_split
#' @importFrom stringr fixed
#' @importFrom dplyr select
#' @export
#' @rdname Features_DecodeParameters
#' @name Features_DecodeParameters
Features_DecodeParameters <- function(preprocessedDFList_reference){
  # Decode parameter sets
  paramSet <- names(preprocessedDFList_reference$"df")
  paramSet <- as.data.frame(t(as.data.frame(stringr::str_split(paramSet, stringr::fixed(".")), fix.empty.names=F)))
  alignTypeSet <- as.numeric(as.character(unique(paramSet[[1]])))
  TCRFragDepthSet <- as.character(unique(paramSet[[2]]))
  seedSet <- as.numeric(as.character(paramSet[[3]]))
  message("Alignment types: ", paste0(alignTypeSet, collapse=", "))
  message("TCR fragment library depths: ", paste0(TCRFragDepthSet, collapse=", "))
  message("Random seeds: ", paste0(seedSet, collapse=", "))

  # Decode additional parameter sets from the selected features
  featureSet <- setdiff(colnames(preprocessedDFList_reference$"train"[[1]]), c("Peptide", "Immunogenicity", "Cluster"))
  featureSet_pept <- grep("PeptDesc_", featureSet, value=T)
  featureSet_pept <- as.data.frame(t(as.data.frame(stringr::str_split(featureSet_pept, stringr::fixed("_")), fix.empty.names=F)))
  fragLenSet_pept <- as.numeric(as.character(unique(featureSet_pept[[3]])))
  featureSet_rTPCP <- grep("rTPCP_", featureSet, value=T)
  featureSet_rTPCP <- as.data.frame(t(as.data.frame(stringr::str_split(featureSet_rTPCP, stringr::fixed("_")), fix.empty.names=F)))
  fragLenSet_rTPCP <- as.numeric(as.character(unique(featureSet_rTPCP[[5]])))
  aaIndexIDSet <- sort(as.character(unique(featureSet_rTPCP[[4]])))
  fragLenSet <- union(fragLenSet_pept, fragLenSet_rTPCP)
  message("Fragment lengths: ", paste0(fragLenSet, collapse=", "))
  message("AAIndex scales: ", paste0(aaIndexIDSet, collapse=", "))

  list("fragLenSet"=fragLenSet,
       "aaIndexIDSet"=aaIndexIDSet,
       "alignTypeSet"=alignTypeSet,
       "TCRFragDepthSet"=TCRFragDepthSet,
       "seedSet"=seedSet)
}

