#' Extract information generated from randomly generated mock sequences
#'
#' @param featureDFList A set of feature dataframes generated by the \code{Features} function.
#' @importFrom dplyr select
#' @importFrom dplyr starts_with
#' @importFrom magrittr set_colnames
#' @importFrom dplyr bind_cols
#' @export
#' @rdname Features_Mock
#' @name Features_Mock
Features_Mock <- function(featureDFList){
  extract.mock.rTPCP <- function(df){
    df_rTPCP <- dplyr::select(df, dplyr::starts_with("rTPCP_"))
    df_pept <- dplyr::select(df, setdiff(colnames(df), colnames(df_rTPCP)))
    mat <- matrix(nrow=nrow(df), ncol=ncol(df_rTPCP)/2)
    id <- sort(unlist(lapply(1:11, function(i){seq(i, ncol(df_rTPCP), 22)})))
    for(i in 1:length(id)){
      mat[,i] <- df_rTPCP[[i]] - df_rTPCP[[i+11]]
    }
    df_rTPCP <- magrittr::set_colnames(as.data.frame(mat), grep("FR_", colnames(df_rTPCP), value=T))
    rm(list=setdiff(ls(), c("df_pept", "df_rTPCP")))
    gc();gc()
    return(list(df_pept, df_rTPCP))
  }
  df_list <- lapply(featureDFList, extract.mock.rTPCP)
  df_pept <- df_list[[1]][[1]]
  df_rTPCP_list <- lapply(df_list, function(l){l[[2]]})
  df_rTPCP_list_diff <- c(df_rTPCP_list, df_rTPCP_list[1])[-1] ## 2,3,4,5,1
  df_rTPCP_list_diff <- mapply(function(d.x, d.y){d.diff <- d.x - d.y; colnames(d.diff) <- gsub("FR_", "Diff_", colnames(d.diff)); d.diff},
                               df_rTPCP_list, df_rTPCP_list_diff, SIMPLIFY=F) ## 1-2, 2-3, 3-4, 4-5, 5-1
  df_list <- lapply(1:length(df_list), function(i){dplyr::bind_cols(df_pept, df_rTPCP_list[[i]], df_rTPCP_list_diff[[i]])})
  names(df_list) <- names(featureDFList)
  rm(list=setdiff(ls(), "df_list"))
  gc();gc()
  return(df_list)
}
