#' Preprocess peptide feature dataframes for machine learning.
#' 
#' @param featureDFList A list of feature dataframes generated by \code{Features}. Can also be a merged output from \code{Features_Merge_} functions.
#' @param metadataDF A metadata dataframe labeled as "Peptide", "Immunogenicity", and "Cluster". No extra metadata is allowed. Feature dataframes are downsized based on the "Peptide" column in this metadata. In other words, peptides not contained in the metadata dataframe are omitted.
#' @importFrom dplyr %>%
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr mutate
#' @importFrom dplyr left_join
#' @importFrom dplyr select
#' @importFrom dplyr one_of
#' @importFrom dplyr bind_rows
#' @importFrom tidyr drop_na
#' @importFrom stringr str_split
#' @importFrom stringr fixed
#' @importFrom rlang set_names
#' @importFrom tibble as_tibble
#' @importFrom DescTools Sort
#' @importFrom caret createDataPartition
#' @importFrom caret preProcess
#' @importFrom caret train
#' @importFrom pbapply timerProgressBar
#' @importFrom pbapply setTimerProgressBar
#' @export
#' @rdname Features_Preprocess
#' @name Features_Preprocess
Features_Preprocess <- function(featureDFList, metadataDF){
  # Working function
  Features_Preprocess_Single <- function(featureDF, metadataDF, seed=12345){
    # Combine metadata
    df <- dplyr::left_join(metadataDF, featureDF, by="Peptide") %>%
      tidyr::drop_na() %>%
      dplyr::mutate(Immunogenicity=factor(Immunogenicity, levels=c("Positive", "Negative")))
    
    # Randomly choose one epitope per each cluster [Minor class is prioritized]
    set.seed(seed)
    outcome_table <- table(df$"Immunogenicity")
    if(outcome_table["Positive"]>=outcome_table["Negative"]){ 
      outcome_minor_major <- c("Negative", "Positive")
    }else{ 
      outcome_minor_major <- c("Positive", "Negative")
    }
    df <- df %>%
      (function(d){d[sample.int(nrow(d)),]}) %>%
      dplyr::mutate(Immunogenicity=factor(Immunogenicity, levels=outcome_minor_major)) %>%
      dplyr::distinct(Immunogenicity, Cluster, .keep_all=T) %>%
      dplyr::distinct(Cluster, .keep_all=T) %>%
      dplyr::distinct(Peptide, .keep_all=T) %>%
      DescTools::Sort(ord=c("Peptide", "Cluster")) %>%
      dplyr::mutate(Immunogenicity=factor(Immunogenicity, levels=c("Positive", "Negative")))
    
    # Random data splitting
    set.seed(seed)
    trainID <- caret::createDataPartition(df$"Immunogenicity", p=7/10, list=F)
    df_train <- df[trainID,] ## Proportion == 0.7
    df_test <- df[-trainID,]
    testID <- caret::createDataPartition(df_test$"Immunogenicity", p=2/3, list=F)
    df_test <- df_test[testID,]   ## Proportion == 0.2
    df_valid <- df_test[-testID,] ## Proportion == 0.1
    
    # Pre-processing
    df_train_features <- dplyr::select(df_train, -Peptide, -Immunogenicity, -Cluster)
    df_train_features <- predict(caret::preProcess(df_train_features, method=c("nzv", "corr")), df_train_features)
    featureSet <- colnames(df_train_features)
    pp_train <- caret::preProcess(df_train_features, method=c("center", "scale"))
    
    df <- predict(pp_train, dplyr::select(df, Peptide, Immunogenicity, Cluster, dplyr::one_of(featureSet)))
    df_train <- predict(pp_train, dplyr::select(df_train, Peptide, Immunogenicity, Cluster, dplyr::one_of(featureSet)))
    df_test <- predict(pp_train, dplyr::select(df_test, Peptide, Immunogenicity, Cluster, dplyr::one_of(featureSet)))
    df_valid <- predict(pp_train, dplyr::select(df_valid, Peptide, Immunogenicity, Cluster, dplyr::one_of(featureSet)))
    
    # Output
    list("df"=df, "df_train"=df_train, "df_test"=df_test, "df_valid"=df_valid)
  }
  
  # Batch preprocessing
  params <- as.data.frame(stringr::str_split(names(featureDFList), stringr::fixed("."), simplify=T), stringsAsFactors=F)
  seedSet <- as.numeric(params[[rev(colnames(params))[1]]])
  l <- length(featureDFList)
  df_list <- rlang::set_names(as.list(numeric(l)), names(featureDFList))
  df_train_list <- rlang::set_names(as.list(numeric(l)), names(featureDFList))
  df_test_list <- rlang::set_names(as.list(numeric(l)), names(featureDFList))
  df_valid_list <- rlang::set_names(as.list(numeric(l)), names(featureDFList))
  if(l==1){
    res <- Features_Preprocess_Single(featureDFList[[1]], metadataDF, seed=seedSet[[1]])
    df_list[[1]] <- res[["df"]]
    df_train_list[[1]] <- res[["df_train"]]
    df_test_list[[1]] <- res[["df_test"]]
    df_valid_list[[1]] <- res[["df_valid"]]
  }else{
    pb <- pbapply::timerProgressBar(min=1, max=l, char="+", style=1)
    for(i in 1:l){
      pbapply::setTimerProgressBar(pb, i)
      res <- Features_Preprocess_Single(featureDFList[[i]], metadataDF, seed=seedSet[[i]])
      df_list[[i]] <- res[["df"]]
      df_train_list[[i]] <- res[["df_train"]]
      df_test_list[[i]] <- res[["df_test"]]
      df_valid_list[[i]] <- res[["df_valid"]]
    }
  }
  tibble::as_tibble(list("df"=df_list, "train"=df_train_list, "test"=df_test_list, "valid"=df_valid_list))
}