#' Decode parameters used for calculating the minimum set of features.
#'
#' \code{Features_MinimumParameters} obtains a set of parameters required for calculation of the minimum set of features used in \code{preprocessedDFList}.\cr
#'
#' @param preprocessedDFList A list of feature dataframes generated by \code{Features_Preprocess}, \code{Features_CorFilter}, or \code{Features_FeatureSelect} for reference.
#' @param criteria Can either be "intersect" or "union".
#' @importFrom stringr str_split
#' @importFrom stringr fixed
#' @importFrom dplyr select
#' @export
#' @rdname Features_MinimumParameters
#' @name Features_MinimumParameters
Features_MinimumParameters <- function(preprocessedDFList, criteria="intersect"){
  # Decode parameter sets
  paramSet <- names(preprocessedDFList)
  paramSet <- t(as.data.frame(stringr::str_split(paramSet, stringr::fixed(".")), fix.empty.names=F))
  clusterTypeSet <- as.character(unique(paramSet[,1]))
  TCRRepertoireTypeSet <- as.character(unique(paramSet[,2]))
  alignTypeSet <- as.character(unique(paramSet[,3]))
  TCRFragDepthSet <- as.numeric(as.character(unique(paramSet[,4])))
  seedSet <- as.numeric(as.character(unique(paramSet[,5])))
  message("Alignment types: ", paste0(alignTypeSet, collapse=", "))
  message("TCR fragment library depths: ", paste0(TCRFragDepthSet, collapse=", "))
  message("Random seeds: ", paste0(seedSet, collapse=", "))

  # Visualize feature overlaps [currently, up to five preprocessed dataframes are supported]
  if(length(preprocessedDFList)<=5){
    featureSet <- lapply(preprocessedDFList, function(l){setdiff(colnames(l$"dt"), c("DataType", "Peptide", "Immunogenicity", "Cluster"))})
    vennDiagram(featureSet, show_category_names=F)
  }

  # Decode additional parameter sets from the minimally selected features
  featureSet <- setdiff(Reduce(criteria, lapply(preprocessedDFList, function(l){colnames(l$"dt")})), c("DataType", "Peptide", "Immunogenicity", "Cluster"))
  featureSet_pept <- grep("PeptDesc_", featureSet, value=T)
  if(length(featureSet_pept)>=1){
    featureSet_pept <- as.data.frame(t(as.data.frame(stringr::str_split(featureSet_pept, stringr::fixed("_")), fix.empty.names=F)))
    fragLenSet_pept <- as.numeric(as.character(unique(featureSet_pept[[4]])))
  }else{
    fragLenSet_pept <- numeric(0)
  }
  featureSet_rTPCP <- grep("rTPCP_", featureSet, value=T)
  if(length(featureSet_rTPCP)>=1){
    featureSet_rTPCP <- as.data.frame(t(as.data.frame(stringr::str_split(featureSet_rTPCP, stringr::fixed("_")), fix.empty.names=F)))
    fragLenSet_rTPCP <- as.numeric(as.character(unique(featureSet_rTPCP[[5]])))
    aaIndexIDSet <- sort(as.character(unique(gsub("inv$", "", featureSet_rTPCP[[4]]))))
  }else{
    fragLenSet_rTPCP <- numeric(0)
    aaIndexIDSet <- character(0)
  }
  fragLenSet <- sort(union(fragLenSet_pept, fragLenSet_rTPCP))
  message("Fragment lengths: ", paste0(fragLenSet, collapse=", "))
  message("AAIndex scales: ", paste0(aaIndexIDSet, collapse=", "))

  # Output
  list("featureSet"=featureSet,
       "fragLenSet"=fragLenSet,
       "aaIndexIDSet"=aaIndexIDSet,
       "alignTypeSet"=alignTypeSet,
       "TCRFragDepthSet"=TCRFragDepthSet,
       "seedSet"=seedSet)
}

