#' Correct errors in the peptide feature dataframes.
#' 
#' @param featureDFList A list of feature dataframes generated by \code{Features}.
#' @param TCRSet Either a set of TCR sequences (as a character vector) or a list of sets of TCR sequences. If provided as a list, it must be the same length with the seedSet.
#' @param aaIndexIDSet A set of AAIndexIDs indicating the pairwise matching score matrix to be used. A set of AAIndex-derived matrices can be retrieved by \code{AACPMatrix}. Set "all" to select all AAIndexIDs.
#' @param fragLenSet A set of the lengths of TCR sequence fragments to be matched against the peptide set.
#' @param alignTypeSet A set of alignment-type strings directly passed to the \code{type} argument of the \code{pairwiseAlignment} function in the \code{Biostrings} package.
#' @param seedSet A set of random seeds.
#' @param TCRFragDepthSet A set of the numbers of TCR fragments to be matched.
#' @importFrom rlang is_empty
#' @importFrom DescTools Sort
#' @importFrom dplyr filter
#' @importFrom dplyr bind_rows
#' @export
#' @rdname Features_ErrorCorrect
#' @name Features_ErrorCorrect
Features_ErrorCorrect <- function(
  featureDFList, TCRSet, 
  aaIndexIDSet="all", alignTypeSet="global-local", 
  fragLenSet=4:6, TCRFragDepthSet=10000, seedSet=1:5
){
  errorPeptideList <- lapply(featureDFList, function(df){df[which(complete.cases(df)==F),][["Peptide"]]})
  featureDFList_ErrorCorrect <- lapply(errorPeptideList, function(peptSet){
    if(rlang::is_empty(peptSet)){
      return(NULL)
    }else{
      Features(peptideSet=peptSet, TCRSet, aaIndexIDSet, alignTypeSet, fragLenSet, TCRFragDepthSet,seedSet)
    }
  })
  featureDFList_ErrorCorrect <- mapply(
    function(org, errCor){
      if(is.null(errCor)){
        DescTools::Sort(org, ord="Peptide")
      }else{
        DescTools::Sort(dplyr::bind_rows(dplyr::filter(org, !Peptide %in% errCor$"Peptide"), errCor), ord="Peptide")
      }
    }, featureDFList, featureDFList_ErrorCorrect, SIMPLIFY=F)
  return(featureDFList_ErrorCorrect)
}