#' Decode parameters used for calculating the minimum set of features.
#'
#' \code{Features_MinimumParameters} obtains a set of parameters required for calculation of the minimum set of features used in \code{preprocessedDFList_reference}.\cr
#'
#' @param preprocessedDFList_reference A list of feature dataframes generated by \code{Features_Preprocess}, \code{Features_CorFilter}, or \code{Features_FeatureSelect} for reference.
#' @param criteria Can either be "intersect" or "union".
#' @importFrom stringr str_split
#' @importFrom stringr fixed
#' @importFrom dplyr select
#' @importFrom VennDiagram venn.diagram
#' @export
#' @rdname Features_MinimumParameters
#' @name Features_MinimumParameters
Features_MinimumParameters <- function(preprocessedDFList_reference, criteria="intersect"){
  # Decode parameter sets
  paramSet <- names(preprocessedDFList_reference)
  paramSet <- t(as.data.frame(stringr::str_split(paramSet, stringr::fixed(".")), fix.empty.names=F))
  clusterTypeSet <- as.character(unique(paramSet[,1]))
  TCRRepertoireTypeSet <- as.character(unique(paramSet[,2]))
  alignTypeSet <- as.character(unique(paramSet[,3]))
  TCRFragDepthSet <- as.numeric(as.character(unique(paramSet[,4])))
  seedSet <- as.numeric(as.character(unique(paramSet[,5])))
  message("Alignment types: ", paste0(alignTypeSet, collapse=", "))
  message("TCR fragment library depths: ", paste0(TCRFragDepthSet, collapse=", "))
  message("Random seeds: ", paste0(seedSet, collapse=", "))

  # Visualize feature overlaps [currently, enabled only in cases where five preprocessed dataframes were provided as references]
  if(length(preprocessedDFList)==5){
    featureSet <- lapply(preprocessedDFList, function(l){setdiff(colnames(l$"dt"), c("DataType", "Peptide", "Immunogenicity", "Cluster"))})
    venn.plot <- VennDiagram::venn.diagram(
      featureSet,
      filename=NULL,
      category.names=rep("", 5),
      col="black",
      fill=c("dodgerblue", "goldenrod1", "darkorange1", "seagreen3", "orchid3"),
      alpha=0.50,
      cex=c(1.5, 1.5, 1.5, 1.5, 1.5, 1, 0.8, 1, 0.8, 1, 0.8, 1, 0.8,
            1, 0.8, 1, 0.55, 1, 0.55, 1, 0.55, 1, 0.55, 1, 0.55, 1, 1, 1, 1, 1, 1.5),
      cat.col=c("dodgerblue", "goldenrod1", "darkorange1", "seagreen3", "orchid3"),
      cat.cex=1.5,
      cat.fontface="bold",
      margin=0.05
    )
    grid::grid.draw(venn.plot)
  }

  # Decode additional parameter sets from the minimally selected features
  featureSet <- setdiff(Reduce(criteria, lapply(preprocessedDFList, function(l){colnames(l$"dt")})), c("DataType", "Peptide", "Immunogenicity", "Cluster"))
  featureSet_pept <- grep("PeptDesc_", featureSet, value=T)
  featureSet_pept <- as.data.frame(t(as.data.frame(stringr::str_split(featureSet_pept, stringr::fixed("_")), fix.empty.names=F)))
  fragLenSet_pept <- as.numeric(as.character(unique(featureSet_pept[[4]])))
  featureSet_rTPCP <- grep("rTPCP_", featureSet, value=T)
  featureSet_rTPCP <- as.data.frame(t(as.data.frame(stringr::str_split(featureSet_rTPCP, stringr::fixed("_")), fix.empty.names=F)))
  fragLenSet_rTPCP <- as.numeric(as.character(unique(featureSet_rTPCP[[5]])))
  fragLenSet <- sort(union(fragLenSet_pept, fragLenSet_rTPCP))
  aaIndexIDSet <- sort(as.character(unique(gsub("inv$", "", featureSet_rTPCP[[4]]))))
  message("Fragment lengths: ", paste0(fragLenSet, collapse=", "))
  message("AAIndex scales: ", paste0(aaIndexIDSet, collapse=", "))

  list("featureSet"=featureSet,
       "fragLenSet"=fragLenSet,
       "aaIndexIDSet"=aaIndexIDSet,
       "alignTypeSet"=alignTypeSet,
       "TCRFragDepthSet"=TCRFragDepthSet,
       "seedSet"=seedSet)
}

