#' Calculate the minimum set of features.
#'
#' \code{Features_DecodeParameters} obtains a set of parameters required for calculation of the minimum set of features used in \code{preprocessedDFList_reference}.\cr
#' \code{Features_Minimum} allows users to generate a set of preprocessed feature dataframes for different sets of peptides and TCR repertoires based on the parameters obtianed by \code{Features_DecodeParameters}.
#'
#' @param peptideSet A set of peptide sequences.
#' @param TCRSet Either a set of TCR sequences (as a character vector) or a list of sets of TCR sequences. If provided as a list, it must be the same length with the seedSet.
#' @param preprocessedDFList_reference A list of feature dataframes generated by \code{Features_Preprocess} for reference.
#' @importFrom stringr str_split
#' @importFrom stringr fixed
#' @importFrom dplyr select
#' @export
#' @rdname Features_Minimum
#' @name Features_Minimum
Features_Minimum <- function(peptideSet, TCRSet, preprocessedDFList_reference){
  # Decode parameters
  paramSet <- Features_DecodeParameters(preprocessedDFList_reference)

  # Calculate features
  featureDFList <- Features(
    peptideSet, TCRSet,
    fragLenSet=paramSet$"fragLenSet",
    aaIndexIDSet=paramSet$"aaIndexIDSet",
    alignTypeSet=paramSet$"alignTypeSet",
    TCRFragDepthSet=paramSet$"TCRFragDepthSet",
    seedSet=paramSet$"seedSet"
  )

  # Preprocessing
  featureSet_reference <- setdiff(colnames(preprocessedDFList_reference$"train"[[1]]), c("Peptide", "Immunogenicity", "Cluster"))
  ppList <- preprocessedDFList$"pp_train"
  preprocessedDFList <- mapply(function(d, pp){
    d.pp <- dplyr::select(d, featureSet_reference)
    d.pp <- predict(pp, d.pp)
    return(d.pp)
  }, featureDFList, ppList, SIMPLIFY=F)

  list("featureDFList"=featureDFList,
       "preprocessedDFList"=preprocessedDFList)
}
