#' Immunogenicity prediction using H2O AutoML instances
#'
#' \code{Immunogenicity} is a wrapper function.
#'
#' @param preprocessedDFList A list of feature dataframes generated by \code{Features_Preprocess}.
#' @param trainDF A dataframe for model training.
#' @param testDF A dataframe for hold-out validation.
#' @param evalDF A dataframe for evaluation.
#' @param destDir A directory for saving outputs.
#' @param LeaderBoardName The file name of the leader board to be saved. The file format must be CSV. If you want to skip saving, set \code{NULL}.
#' @param H2OModelName The file name of the best H2O model to be saved. No file extension is required. If you want to skip saving, set \code{NULL}.
#' @param PredictionHeader The file name header of the prediction results to be saved.
#' @param seed A random seed.
#' @param max_mem_size The upper limit of memory for H2O Java machine learning engine.
#' @param nthreads The number of threads for H2O Java machine learning engine.
#' @importFrom dplyr %>%
#' @importFrom dplyr select
#' @importFrom dplyr mutate
#' @importFrom dplyr bind_cols
#' @importFrom readr write_csv
#' @importFrom stringr str_split
#' @importFrom stringr fixed
#' @importFrom data.table rbindlist
#' @importFrom caret downSample
#' @importFrom pROC coords
#' @importFrom pROC roc
#' @importFrom classifierplots roc_plot
#' @importFrom classifierplots calibration_plot
#' @importFrom plotUtility theme_Publication
#' @importFrom plotUtility savePDF
#' @import h2o
#' @import ggplot2
#' @export
#' @rdname ImmunogenicityPrediction
#' @name ImmunogenicityPrediction
Immunogenicity <- function(
  preprocessedDFList, destDir="./Results/", max_mem_size="6G", nthreads=6
){
  dir.create(destDir, showWarnings=F, recursive=T)
  h2o::h2o.init(ip="localhost", max_mem_size=max_mem_size, nthreads=nthreads)

  leng <- length(preprocessedDFList$"df")
  df_lb_list <- as.list(rep(NA, leng))
  df_pred_list <- as.list(rep(NA, leng))
  cat("Number of datasets = ", leng, "\n", sep="")

  # Train classifiers
  cat("Train classifiers...\n")
  for(i in 1:leng){
    param <- names(preprocessedDFList$"df")[i]
    s <- as.integer(rev(unlist(stringr::str_split(param, stringr::fixed("."))))[1])
    modName <- paste0("BestH2OModel_", param)
    cat("Random seed = ", s, "\n", sep="")
    skipQ <- file.exists(file.path(destDir, modName))
    if(skipQ==F){
      df_lb_list[[i]] <- Immunogenicity_AutoML(
        preprocessedDFList$"train"[[i]], preprocessedDFList$"test"[[i]],
        destDir=destDir, LeaderBoardName=NULL, H2OModelName=modName,
        seed=s, max_mem_size=max_mem_size, nthreads=nthreads
      ) %>% dplyr::mutate("Parameter"=param, "Seed"=s)
    }else{
      cat("Model training was skipped.\n")
    }
  }
  df_lb <- data.table::rbindlist(df_lb_list)
  readr::write_csv(df_lb, file.path(destDir, "LeaderBoard.csv"))

  # Evaluate performances
  cat("Evaluate performances in validation subdataset...\n")
  for(i in 1:leng){
    param <- names(preprocessedDFList$"df")[i]
    s <- as.integer(rev(unlist(stringr::str_split(param, stringr::fixed("."))))[1])
    modName <- paste0("BestH2OModel_", param)
    cat("Random seed = ", s, "\n", sep="")
    df_pred_list[[i]] <- Immunogenicity_Prediction(
      preprocessedDFList$"valid"[[i]],
      destDir=destDir, H2OModelName=modName, PredictionHeader="Predictions_Valid_",
      seed=s, max_mem_size=max_mem_size, nthreads=nthreads
    ) %>% dplyr::mutate("Parameter"=param, "Seed"=s)
  }
  df_pred <- data.table::rbindlist(df_pred_list)
  readr::write_csv(df_pred, file.path(destDir, paste0("Predictions_Valid_", param, ".csv")))
  return(list("LeaderBoard"=df_lb, "Prediction"=df_pred))
}

#' @export
#' @rdname ImmunogenicityPrediction
#' @name ImmunogenicityPrediction
Immunogenicity_AutoML <- function(
  trainDF, testDF,
  destDir="./Results/", LeaderBoardName="LeaderBoard.csv", H2OModelName="BestH2OModel",
  seed=12345, max_mem_size="6G", nthreads=6
){
  set.seed(seed)
  dir.create(destDir, showWarnings=F, recursive=T)
  h2o::h2o.init(ip="localhost", max_mem_size=max_mem_size, nthreads=nthreads)

  # Level check
  trainDF$"Immunogenicity" <- factor(trainDF$"Immunogenicity", levels=c("Positive", "Negative"))
  testDF$"Immunogenicity" <- factor(testDF$"Immunogenicity", levels=c("Positive", "Negative"))

  # Down-sampling to avoid class imbalance
  trainDF <- caret::downSample(dplyr::select(trainDF, -Immunogenicity), trainDF$"Immunogenicity", yname="Immunogenicity") %>%
    dplyr::select(Immunogenicity, setdiff(colnames(.), "Immunogenicity"))

  # Train immunogenicity classifiers
  df_train <- h2o::as.h2o(trainDF)
  df_test <- h2o::as.h2o(testDF)
  aml <- h2o::h2o.automl(
    x=setdiff(colnames(trainDF), c("Immunogenicity", "Peptide", "Cluster")),  ## remove metadata to avoid leakage
    y="Immunogenicity",
    training_frame=df_train,
    validation_frame=df_test,
    max_models=100,
    stopping_metric="AUTO",
    stopping_tolerance=0.05,
    stopping_rounds=5,
    seed=seed
  )
  df_lb <- as.data.frame(aml@leaderboard)
  if(!is.null(LeaderBoardName)) readr::write_csv(df_lb, file.path(destDir, LeaderBoardName))

  # Save the best classifier
  best_model_name <- df_lb[["model_id"]][[1]]
  best_model <- h2o::h2o.getModel(best_model_name)
  if(!is.null(H2OModelName)){
    h2o::h2o.saveModel(object=best_model, path=destDir, force=T)
    invisible(file.copy(
      from=file.path(destDir, best_model_name),
      to=file.path(destDir, H2OModelName),
      overwrite=T
    ))
    invisible(file.remove(file.path(destDir, best_model_name)))
  }

  return(df_lb)
}

#' @export
#' @rdname ImmunogenicityPrediction
#' @name ImmunogenicityPrediction
Immunogenicity_Prediction <- function(
  evalDF, destDir="./Results/", H2OModelName="BestH2OModel", PredictionHeader="Predictions_",
  seed=12345, max_mem_size="6G", nthreads=6
){
  # Working environment
  set.seed(seed)
  dir.create(destDir, showWarnings=F, recursive=T)
  h2o::h2o.init(ip="localhost", max_mem_size=max_mem_size, nthreads=nthreads)

  # Immunogenicity prediction
  evalH2ODF <- h2o::as.h2o(evalDF)
  H2OMod <- h2o::h2o.loadModel(file.path(destDir, H2OModelName))
  predDF <- as.data.frame(predict(H2OMod, evalH2ODF))
  colnames(predDF)[1] <- "PredictedImmunogenicity"
  predDF <- dplyr::bind_cols(dplyr::select(evalDF, c("Peptide", "Immunogenicity")), predDF)
  saveRDS(predDF, file.path(destDir, paste0(PredictionHeader, "Results_Seed", seed, ".rds")))

  # Probability distribution plot
  thr <- pROC::coords(pROC::roc(predDF$"Immunogenicity", predDF$"Positive"), "b", ret="t", best.method="youden")[1] ## Two or more threshold could sometimes be returned... The first one is the lowest, meaning maximum sensitivity for P.aeruginosa.
  probPlot <- ggplot(data=predDF, aes_string(x="Immunogenicity", y="Positive")) +
    geom_jitter(width=0.2) + geom_hline(yintercept=thr, color="grey50", size=1) +
    xlab(NULL) + ylab("Immunogenicity score") +
    plotUtility::theme_Publication()
  plotUtility::savePDF(probPlot, outputFileName=file.path(destDir, paste0(PredictionHeader, "JitterPlot_Seed", seed, ".pdf")))

  # Classifier plots
  rocPlot <- classifierplots::roc_plot(2-as.numeric(predDF$"Immunogenicity"), predDF$"Positive") +
    plotUtility::theme_Publication()
  plotUtility::savePDF(rocPlot, outputFileName=file.path(destDir, paste0(PredictionHeader, "ROCPlot_Seed", seed, ".pdf")))
  calibPlot <- classifierplots::calibration_plot(2-as.numeric(predDF$"Immunogenicity"), predDF$"Positive") +
    plotUtility::theme_Publication()
  plotUtility::savePDF(calibPlot, outputFileName=file.path(destDir, paste0(PredictionHeader, "CalibrationPlot_Seed", seed, ".pdf")))

  return(predDF)
}
