#' Immunogenicity score.
#'
#' \code{Immunogenicity_TrainModels} trains extremely randomized tree models, and internally predicts immunogenicity scores on the entire dataset provided.\cr
#' \code{Immunogenicity_SummarizeInternalScores} summarizes internally calculated immunogenicity scores.\cr
#' \code{Immunogenicity_Score} is a wrapper function of \code{Immunogenicity_TrainModels} and \code{Immunogenicity_SummarizeInternalScores}.\cr
#' \code{Immunogenicity_Score_Cluster} is similar to \code{Immunogenicity_Score}, but takes \code{clusterDF} to filter peptides based on their similarities.\cr
#' \code{Immunogenicity_Predict} predicts immunogenicity scores on external datasets. Models trained by \code{Immunogenicity_TrainModels} are necessary. Note that, due to Java constraints, models have to be constructed in each new R session.
#'
#' @param featureDF A dataframe of features generated by \code{Features}.
#' @param metadataDF A dataframe containing metadata, consisting of "Peptide" and "Immunogenicity" columns. Other columns if provided would be used as features.
#' @param clusterDF A dataframe containing cluster metadata, consisting of "Peptide" and "Cluster" columns.
#' @param featureSet A set of features used for model training. Set "all" to shortcut.
#' @param seedSet A set of random seeds.
#' @param coreN The number of cores to be used for parallelization. Set \code{NULL} to disable.
#' @param trainModelResults The model training result returned by \code{Immunogenicity_TrainModels}.
#' @param externalFeatureDFList The feature dataframes for which immunogenicity is to be predicted.
#' @importFrom dplyr %>%
#' @importFrom dplyr transmute
#' @importFrom dplyr select
#' @importFrom dplyr left_join
#' @importFrom dplyr right_join
#' @importFrom dplyr group_by
#' @importFrom dplyr summarise
#' @importFrom dplyr distinct
#' @importFrom purrr flatten
#' @importFrom purrr flatten_dfr
#' @importFrom data.table :=
#' @importFrom data.table rbindlist
#' @importFrom data.table as.data.table
#' @importFrom caret preProcess
#' @importFrom extraTrees extraTrees
#' @importFrom BBmisc chunk
#' @importFrom parallel detectCores
#' @importFrom pbapply pblapply
#' @export
#' @rdname Immunogenicity
#' @name Immunogenicity
Immunogenicity_TrainModels <- function(
  featureDF,
  metadataDF,
  featureSet="all",
  seedSet=1:5,
  coreN=parallel::detectCores()
){
  # A combined feature dataframe
  dt <- merge(data.table::as.data.table(metadataDF), data.table::as.data.table(featureDF), by="Peptide")
  if(identical(featureSet, "all")){
    featureSet <- setdiff(colnames(dt), c("Peptide", "Immunogenicity"))
  }else{
    dt <- dt[, c("Peptide", "Immunogenicity", featureSet), with=F]
  }
  dt[,"Immunogenicity":=factor(Immunogenicity, levels=c("Positive", "Negative"))]

  # Random splitting
  trainIDList <- lapply(seedSet, function(s){set.seed(s);lapply(BBmisc::chunk(1:nrow(dt), n.chunks=5, shuffle=T), function(v){setdiff(1:nrow(dt), v)})})

  # The main workflow
  main <- function(dt, trainIDs){
    dt_train <- dt[trainIDs,]
    dt_test <- dt[-trainIDs,]
    pp_train <- caret::preProcess(dt_train[, featureSet, with=F], method=c("center", "scale"))
    dt_train <- predict(pp_train, dt_train)
    dt_test <- predict(pp_train, dt_test)
    trgt <- dt_train$"Immunogenicity"
    tab <- as.numeric(table(trgt))
    w <- 1/tab[trgt]
    mat_train <- as.matrix(dt_train[, featureSet, with=F])
    ert <- extraTrees::extraTrees(
      x=mat_train, y=trgt,
      mtry=35, numRandomCuts=2, weights=w,
      numThreads=ifelse(is.null(coreN), 1, coreN)
    )
    mat_test <- as.matrix(dt_test[, featureSet, with=F])
    predDT <- data.table::data.table("Peptide"=dt_test$"Peptide")
    predDT[,"ImmunogenicityScore":=predict(ert, mat_test, probability=T)[,"Positive"]]
    return(list(
      "pp_train"=pp_train, "ert"=ert, "predDT"=predDT
    ))
  }
  resList <- foreach::foreach(i=1:length(seedSet))%do%{
    cat("Random seed = ", seedSet[i], "\n", sep="")
    pbapply::pblapply(trainIDList[[i]], function(trainIDs){main(dt, trainIDs)})
  }
  return(list("TrainModelResults"=resList, "FeatureSet"=featureSet, "SeedSet"=seedSet))
}

#' @export
#' @rdname Immunogenicity
#' @name Immunogenicity
Immunogenicity_SummarizeInternalScores <- function(trainModelResults){
  dt_score <- lapply(trainModelResults$"TrainModelResults", function(res){lapply(res, function(r){r$"predDT"})}) %>%
    purrr::flatten() %>%
    data.table::rbindlist()
  dt_score <- dt_score[, mean(ImmunogenicityScore), by="Peptide"][, sd(ImmunogenicityScore), by="Peptide"]
  colnames(dt_score) <- c("Peptide", "ImmunogenicityScore", "ImmunogenicityScore.sd")
  return(dt_score)
}

#' @export
#' @rdname Immunogenicity
#' @name Immunogenicity
Immunogenicity_Score <- function(
  featureDF,
  metadataDF,
  featureSet="all",
  seedSet=1:5,
  coreN=parallel::detectCores()
){
  trainModelResults <- Immunogenicity_TrainModels(featureDF, metadataDF, featureSet, seedSet, coreN)
  dt_score <- Immunogenicity_SummarizeInternalScores(trainModelResults)
  return(dt_score)
}

#' @export
#' @rdname Immunogenicity
#' @name Immunogenicity
Immunogenicity_Score_Cluster <- function(
  featureDF,
  metadataDF,
  clusterDF,
  featureSet="all",
  seedSet=1:5,
  coreN=parallel::detectCores()
){
  dt_score <- lapply(seedSet, function(s){
    set.seed(s)
    peptideSet <- clusterDF[sample(1:nrow(clusterDF)),] %>% dplyr::distinct(Cluster, .keep_all=T)
    peptideSet <- peptideSet[["Peptide"]]
    dt_score <- Immunogenicity_Score(
      featureDF=dplyr::filter(featureDF, Peptide %in% peptideSet),
      metadataDF=dplyr::filter(metadataDF, Peptide %in% peptideSet),
      featureSet=featureSet,
      seedSet=s,
      coreN=coreN
    )
    return(dt_score)
  }) %>%
    data.table::rbindlist()
  dt_score <- dt_score[, mean(ImmunogenicityScore), by="Peptide"][, sd(ImmunogenicityScore), by="Peptide"]
  colnames(dt_score) <- c("Peptide", "ImmunogenicityScore", "ImmunogenicityScore.sd")
  return(dt_score)
}

#' @export
#' @rdname Immunogenicity
#' @name Immunogenicity
Immunogenicity_Predict <- function(externalFeatureDFList, trainModelResults){
  featureSet <- trainModelResults$"FeatureSet"
  pp_list <- purrr::flatten(
    lapply(trainModelResults$"TrainModelResults", function(res){lapply(res, function(r){r$"pp_train"})})
  )
  ert_list <- purrr::flatten(
    lapply(trainModelResults$"TrainModelResults", function(res){lapply(res, function(r){r$"ert"})})
  )
  scoreDT_list <- foreach::foreach(i=1:length(externalFeatureDFList))%do%{
    cat("Data set #", i, "\n", sep="")
    dt <- data.table::as.data.table(externalFeatureDFList[[i]])
    dt_score <- pbapply::pblapply(1:length(pp_list), function(j){
      mat <- as.matrix(predict(pp_list[[j]], dt[, featureSet, with=F]))
      predDT <- data.table::data.table("Peptide"=dt$"Peptide")
      predDT[,"ImmunogenicityScore":=predict(ert, mat_test, probability=T)[,"Positive"]]
      return(predDT)
    }) %>%
      data.table::rbindlist()
    dt_score <- dt_score[, mean(ImmunogenicityScore), by="Peptide"][, sd(ImmunogenicityScore), by="Peptide"]
    colnames(dt_score) <- c("Peptide", "ImmunogenicityScore", "ImmunogenicityScore.sd")
    return(dt_score)
  }
  return(scoreDT_list)
}
